"""Generate fixed-array C data for ``tools/l2_meta_asm_runner.c``.

The generated header is an artifact-specific acceleration structure for one L2
``.utm.band`` file. It keeps the runtime loop in C simple: tokens become integer
IDs, register/rule/cell offsets are precomputed, and the runner can execute the
MetaASM universal-machine blocks without Python objects or textual lookups.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from mtm.semantic_objects import UTMBandArtifact
from mtm.source_encoding import L, R, encode_direction, encode_state
from mtm.utm_band_layout import (
    CELL,
    CUR_STATE,
    CUR_SYMBOL,
    END_RULE,
    END_RULES,
    HEAD,
    MOVE,
    MOVE_DIR,
    NEXT,
    NEXT_STATE,
    NO_HEAD,
    READ,
    RULE,
    RULES,
    STATE,
    TAPE_LEFT,
    WRITE,
    WRITE_SYMBOL,
)


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate C tables for the L2 MetaASM runner.")
    parser.add_argument("band_file", help="Path to an L2 .utm.band artifact.")
    parser.add_argument("-o", "--output", required=True, help="Output header path, usually l2_meta_asm_data.h.")
    parser.add_argument("--left-margin", type=int, default=16, help="Unused spare cells in the mutable left token array.")
    parser.add_argument("--right-margin", type=int, default=16, help="Unused spare cells in the mutable right token array.")
    return parser


def _token_name(token: str) -> str:
    names = {
        "0": "TOK_0",
        "1": "TOK_1",
        CELL: "TOK_CELL",
        HEAD: "TOK_HEAD",
        NO_HEAD: "TOK_NO_HEAD",
    }
    return names[token]


def _global_field_start(left: tuple[str, ...], marker: str) -> int:
    return left.index(marker) + 1


def _local_field_start(left: tuple[str, ...], rule_start: int, marker: str) -> int:
    rule_end = left.index(END_RULE, rule_start + 1)
    index = rule_start + 1
    while index < rule_end:
        if left[index] == marker:
            return index + 1
        index += 1
    raise ValueError(f"missing {marker} in rule at {rule_start}")


def _rule_starts(left: tuple[str, ...]) -> list[int]:
    starts: list[int] = []
    index = left.index(RULES) + 1
    while left[index] != END_RULES:
        if left[index] != RULE:
            raise ValueError(f"expected {RULE} at {index}, got {left[index]!r}")
        starts.append(index)
        index = left.index(END_RULE, index + 1) + 1
    return starts


def _left_cell_starts(left: tuple[str, ...]) -> list[int]:
    tape_left = left.index(TAPE_LEFT)
    return [index for index, token in enumerate(left[:tape_left]) if token == CELL]


def _right_cell_starts(right: tuple[str, ...]) -> list[int]:
    return [index for index, token in enumerate(right) if token == CELL]


def _head_position(left: tuple[str, ...], right: tuple[str, ...]) -> tuple[int, int]:
    left_cells = _left_cell_starts(left)
    for ordinal, index in enumerate(left_cells):
        if left[index + 1] == HEAD:
            return 0, ordinal
    right_cells = _right_cell_starts(right)
    for ordinal, index in enumerate(right_cells):
        if right[index + 1] == HEAD:
            return 1, ordinal
    raise ValueError("encoded band has no simulated head")


def _array(name: str, values: list[int] | tuple[int, ...], *, ctype: str = "int") -> list[str]:
    lines = [f"static const {ctype} {name}[] = {{"]
    row: list[str] = []
    for value in values:
        row.append(str(value))
        if len(row) == 24:
            lines.append("  " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("  " + ", ".join(row) + ",")
    lines.append("};")
    return lines


def generate_header(band_file: Path, *, left_margin: int, right_margin: int) -> str:
    artifact = UTMBandArtifact.read(band_file)
    left = artifact.left_band
    right = artifact.right_band
    encoding = artifact.encoding

    tokens = sorted(set(left) | set(right) | {"0", "1"})
    token_ids = {token: index for index, token in enumerate(tokens)}
    left_ids = [token_ids[token] for token in left]
    right_ids = [token_ids[token] for token in right]
    rule_starts = _rule_starts(left)
    left_cells = _left_cell_starts(left)
    right_cells = _right_cell_starts(right)
    sim_side, sim_cell = _head_position(left, right)

    lines = [
        "/* Generated by tools/generate_l2_meta_asm_data.py. */",
        "#pragma once",
        f"#define LEFT_LEN {len(left_ids)}",
        f"#define RIGHT_LEN {len(right_ids)}",
        f"#define LEFT_CAP {len(left_ids) + left_margin}",
        f"#define RIGHT_CAP {len(right_ids) + right_margin}",
        f"#define RULE_COUNT {len(rule_starts)}",
        f"#define LEFT_CELL_COUNT {len(left_cells)}",
        f"#define RIGHT_CELL_COUNT {len(right_cells)}",
        f"#define STATE_WIDTH {encoding.state_width}",
        f"#define SYMBOL_WIDTH {encoding.symbol_width}",
        f"#define DIR_WIDTH {encoding.direction_width}",
        f"#define G_CUR_STATE {_global_field_start(left, CUR_STATE)}",
        f"#define G_CUR_SYMBOL {_global_field_start(left, CUR_SYMBOL)}",
        f"#define G_WRITE_SYMBOL {_global_field_start(left, WRITE_SYMBOL)}",
        f"#define G_NEXT_STATE {_global_field_start(left, NEXT_STATE)}",
        f"#define G_MOVE_DIR {_global_field_start(left, MOVE_DIR)}",
        f"#define SIM_SIDE_INIT {sim_side}",
        f"#define SIM_CELL_INIT {sim_cell}",
        f"#define SOURCE_SYMBOL_COUNT {len(encoding.id_symbols)}",
    ]
    for token in ("0", "1", CELL, HEAD, NO_HEAD):
        lines.append(f"#define {_token_name(token)} {token_ids[token]}")

    lines.extend(_array("LEFT_INIT", left_ids))
    lines.extend(_array("RIGHT_INIT", right_ids))
    lines.extend(_array("LEFT_CELL_STARTS", left_cells))
    lines.extend(_array("RIGHT_CELL_STARTS", right_cells))
    lines.extend(_array("HALT_BITS", [token_ids[bit] for bit in encode_state(encoding, encoding.halt_state)]))
    lines.extend(_array("LEFT_BITS", [token_ids[bit] for bit in encode_direction(encoding, L)]))
    lines.extend(_array("RIGHT_BITS", [token_ids[bit] for bit in encode_direction(encoding, R)]))
    lines.extend(_array("RULE_STATE_START", [_local_field_start(left, start, STATE) for start in rule_starts]))
    lines.extend(_array("RULE_READ_START", [_local_field_start(left, start, READ) for start in rule_starts]))
    lines.extend(_array("RULE_WRITE_START", [_local_field_start(left, start, WRITE) for start in rule_starts]))
    lines.extend(_array("RULE_NEXT_START", [_local_field_start(left, start, NEXT) for start in rule_starts]))
    lines.extend(_array("RULE_MOVE_START", [_local_field_start(left, start, MOVE) for start in rule_starts]))
    lines.append("static const char *SOURCE_SYMBOLS[] = {")
    for index in range(len(encoding.id_symbols)):
        lines.append(f"  {json.dumps(encoding.id_symbols[index])},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main() -> int:
    args = _build_parser().parse_args()
    if args.left_margin < 0 or args.right_margin < 0:
        raise SystemExit("margins must be nonnegative")
    Path(args.output).write_text(
        generate_header(
            Path(args.band_file),
            left_margin=args.left_margin,
            right_margin=args.right_margin,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
