"""Generate fixed-array data for ``tools/l1_raw_guest_runner.c``.

The generated header contains integer IDs for the L1 raw states/symbols, the
raw transition table, and the initial L1 runtime tape. This intentionally
supports a direct L1 raw-guest sanity check only; it is not the L2 MetaASM proof
and not the lowered L2 raw transition run.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from mtm.semantic_objects import UTMBandArtifact, UTMProgramArtifact


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate C data tables for the L1 raw guest runner.")
    parser.add_argument("tm_file", help="Path to an L1 .tm artifact.")
    parser.add_argument("band_file", help="Path to the matching L1 .utm.band artifact.")
    parser.add_argument("-o", "--output", required=True, help="Output header path, usually l1_raw_guest_data.h.")
    parser.add_argument("--margin", type=int, default=1000, help="Blank fixed-tape margin on both sides.")
    parser.add_argument("--right-dump-cells", type=int, default=None, help="How many raw nonnegative cells to print.")
    return parser


def _c_string(value: str) -> str:
    return json.dumps(value)


def generate_header(tm_file: Path, band_file: Path, *, margin: int, right_dump_cells: int | None) -> str:
    program = UTMProgramArtifact.read(tm_file).program
    band = UTMBandArtifact.read(band_file)
    runtime_tape = band.to_runtime_tape()

    states = {program.start_state, program.halt_state}
    symbols = set(program.alphabet) | set(runtime_tape.values()) | {program.blank}
    for (state, read_symbol), (next_state, write_symbol, _move) in program.transitions.items():
        states.update((state, next_state))
        symbols.update((read_symbol, write_symbol))

    state_ids = {state: index for index, state in enumerate(sorted(states))}
    symbol_ids = {symbol: index for index, symbol in enumerate(sorted(symbols))}
    low, high = min(runtime_tape), max(runtime_tape)
    origin = margin - low
    tape_size = (high - low + 1) + margin * 2
    dump_cells = len(band.right_band) if right_dump_cells is None else right_dump_cells

    rules = [
        (state_ids[state], symbol_ids[read_symbol], state_ids[next_state], symbol_ids[write_symbol], move)
        for (state, read_symbol), (next_state, write_symbol, move) in program.transitions.items()
    ]
    init = [(address + origin, symbol_ids[symbol]) for address, symbol in sorted(runtime_tape.items())]

    lines = [
        "/* Generated by tools/generate_l1_raw_guest_data.py. */",
        "#pragma once",
        f"#define TAPE_SIZE {tape_size}",
        f"#define RULE_COUNT {len(rules)}",
        f"#define INIT_COUNT {len(init)}",
        f"#define ORIGIN {origin}",
        f"#define BLANK {symbol_ids[program.blank]}",
        f"#define HALT {state_ids[program.halt_state]}",
        f"#define START_STATE {state_ids[program.start_state]}",
        f"#define START_HEAD {band.start_head + origin}",
        f"#define RIGHT_DUMP_CELLS {dump_cells}",
        "static const char *SYMBOLS[] = {",
    ]
    for symbol, _index in sorted(symbol_ids.items(), key=lambda item: item[1]):
        lines.append(f"  {_c_string(symbol)},")
    lines.extend(["};", "static const Rule RULES[] = {"])
    for state, read_symbol, next_state, write_symbol, move in rules:
        lines.append(f"  {{{state}, {read_symbol}, {next_state}, {write_symbol}, {move}}},")
    lines.extend(["};", "static const int INIT[][2] = {"])
    for address, symbol in init:
        lines.append(f"  {{{address}, {symbol}}},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main() -> int:
    args = _build_parser().parse_args()
    if args.margin < 0:
        raise SystemExit("--margin must be nonnegative")
    if args.right_dump_cells is not None and args.right_dump_cells < 0:
        raise SystemExit("--right-dump-cells must be nonnegative")

    output = Path(args.output)
    output.write_text(
        generate_header(
            Path(args.tm_file),
            Path(args.band_file),
            margin=args.margin,
            right_dump_cells=args.right_dump_cells,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
