"""Generate fixed-array C data for ``tools/raw_tm_runner.c``.

The generated header specializes one raw ``.tm`` artifact and one ``.utm.band``
input into integer IDs, dense transition tables, and initial tape contents.
It is meant for fast bounded experiments with real lowered raw transition
programs, including cross-ABI checks such as running a wider UTM host over a
narrower band.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from mtm.semantic_objects import UTMBandArtifact, UTMProgramArtifact
from mtm.utm_band_layout import CELL, END_CELL, HEAD, NO_HEAD


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate C data tables for the generic raw TM runner.")
    parser.add_argument("tm_file", help="Path to a raw .tm artifact.")
    parser.add_argument("band_file", help="Path to the initial .utm.band artifact.")
    parser.add_argument("-o", "--output", required=True, help="Output header path, usually raw_tm_runner_data.h.")
    parser.add_argument("--margin", type=int, default=1000, help="Blank fixed-tape margin on both sides.")
    parser.add_argument("--right-dump-cells", type=int, default=None, help="How many decoded nonnegative cells to print.")
    parser.add_argument("--raw-dump-cells", type=int, default=0, help="How many raw nonnegative tape cells to print.")
    return parser


def _c_string(value: str) -> str:
    return json.dumps(value)


def _array(name: str, values: list[int] | tuple[int, ...], *, ctype: str = "int") -> list[str]:
    lines = [f"static const {ctype} {name}[] = {{"]
    row: list[str] = []
    for value in values:
        row.append(str(value))
        if len(row) == 24:
            lines.append("  " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("  " + ", ".join(row) + ",")
    lines.append("};")
    return lines


def _token_define_name(token: str) -> str:
    names = {
        "0": "TOK_0",
        "1": "TOK_1",
        CELL: "TOK_CELL",
        HEAD: "TOK_HEAD",
        NO_HEAD: "TOK_NO_HEAD",
        END_CELL: "TOK_END_CELL",
    }
    return names[token]


def generate_header(tm_file: Path, band_file: Path, *, margin: int, right_dump_cells: int | None, raw_dump_cells: int) -> str:
    program_artifact = UTMProgramArtifact.read(tm_file)
    program = program_artifact.program
    band = UTMBandArtifact.read(band_file)
    runtime_tape = band.to_runtime_tape()

    states = {program.start_state, program.halt_state}
    symbols = set(program.alphabet) | set(runtime_tape.values()) | {program.blank}
    for (state, read_symbol), (next_state, write_symbol, _move) in program.transitions.items():
        states.update((state, next_state))
        symbols.update((read_symbol, write_symbol))

    state_ids = {state: index for index, state in enumerate(sorted(states))}
    symbol_ids = {symbol: index for index, symbol in enumerate(sorted(symbols))}
    state_count = len(state_ids)
    symbol_count = len(symbol_ids)

    table_size = state_count * symbol_count
    next_table = [-1] * table_size
    write_table = [-1] * table_size
    move_table = [0] * table_size
    for (state, read_symbol), (next_state, write_symbol, move) in program.transitions.items():
        offset = state_ids[state] * symbol_count + symbol_ids[read_symbol]
        next_table[offset] = state_ids[next_state]
        write_table[offset] = symbol_ids[write_symbol]
        move_table[offset] = move

    low, high = min(runtime_tape), max(runtime_tape)
    origin = margin - low
    tape_size = (high - low + 1) + margin * 2
    init = [(address + origin, symbol_ids[symbol]) for address, symbol in sorted(runtime_tape.items())]
    dump_cells = len(band.right_band) if right_dump_cells is None else right_dump_cells

    lines = [
        "/* Generated by tools/generate_raw_tm_runner_data.py. */",
        "#pragma once",
        f"#define TAPE_SIZE {tape_size}",
        f"#define STATE_COUNT {state_count}",
        f"#define SYMBOL_COUNT {symbol_count}",
        f"#define TABLE_SIZE {table_size}",
        f"#define INIT_COUNT {len(init)}",
        f"#define ORIGIN {origin}",
        f"#define BLANK {symbol_ids[program.blank]}",
        f"#define HALT {state_ids[program.halt_state]}",
        f"#define START_STATE {state_ids[program.start_state]}",
        f"#define START_HEAD {band.start_head + origin}",
        f"#define RIGHT_TOKEN_COUNT {len(band.right_band)}",
        f"#define RIGHT_DUMP_CELLS {dump_cells}",
        f"#define RAW_DUMP_CELLS {raw_dump_cells}",
        f"#define SOURCE_SYMBOL_COUNT {len(band.encoding.id_symbols)}",
        f"#define SOURCE_SYMBOL_WIDTH {band.encoding.symbol_width}",
    ]
    for token in ("0", "1", CELL, HEAD, NO_HEAD, END_CELL):
        if token in symbol_ids:
            lines.append(f"#define {_token_define_name(token)} {symbol_ids[token]}")

    lines.append("static const char *STATES[] = {")
    for state, _index in sorted(state_ids.items(), key=lambda item: item[1]):
        lines.append(f"  {_c_string(state)},")
    lines.append("};")
    lines.append("static const char *SYMBOLS[] = {")
    for symbol, _index in sorted(symbol_ids.items(), key=lambda item: item[1]):
        lines.append(f"  {_c_string(symbol)},")
    lines.append("};")
    lines.append("static const char *SOURCE_SYMBOLS[] = {")
    for index in range(len(band.encoding.id_symbols)):
        lines.append(f"  {_c_string(band.encoding.id_symbols[index])},")
    lines.append("};")
    lines.extend(_array("NEXT_TABLE", next_table))
    lines.extend(_array("WRITE_TABLE", write_table))
    lines.extend(_array("MOVE_TABLE", move_table))
    lines.append("static const int INIT[][2] = {")
    for address, symbol in init:
        lines.append(f"  {{{address}, {symbol}}},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main() -> int:
    args = _build_parser().parse_args()
    if args.margin < 0:
        raise SystemExit("--margin must be nonnegative")
    if args.right_dump_cells is not None and args.right_dump_cells < 0:
        raise SystemExit("--right-dump-cells must be nonnegative")
    if args.raw_dump_cells < 0:
        raise SystemExit("--raw-dump-cells must be nonnegative")

    Path(args.output).write_text(
        generate_header(
            Path(args.tm_file),
            Path(args.band_file),
            margin=args.margin,
            right_dump_cells=args.right_dump_cells,
            raw_dump_cells=args.raw_dump_cells,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
